language: scala

scala:
  - 2.13.3

jdk:
  - oraclejdk8

sudo: false

dist: trusty

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  - $HOME/.cache/coursier

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++${TRAVIS_SCALA_VERSION} clean &&
    sbt ++${TRAVIS_SCALA_VERSION} compile &&
    sbt ++${TRAVIS_SCALA_VERSION} coulomb_testsJVM/test coulomb_testsJS/test
